In [20]:
# SOS & EOS swapper
import torch
import numpy as np
from torch import tensor

# Make sure SOS and EOS exist and are distinct!!

shp = (12, 4)

gts = np.array(range(np.product(shp))).reshape(shp)



# Start / end point             
diff =  np.sum(abs(preds.reshape(-1, 2) - gts.reshape(-1, 2)), axis=1)
diff2 = np.sum(abs(preds.reshape(-1, 2) - gts.reshape(-1, 2)[:,::-1]),axis=1)
loss = np.minimum(diff,diff2)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [28]:
# SOS & EOS swapper
import torch
import numpy as np
from torch import tensor

# Make sure SOS and EOS exist and are distinct!!

shp = (12, 4)

gts = np.array(range(np.product(shp))).reshape(shp)
gts = tensor(gts)
preds = tensor(preds)
# Start / end point             
diff =  torch.sum(torch.abs(preds.reshape(-1, 2) - gts.reshape(-1, 2)), axis=1)
diff2 = torch.sum(torch.abs(preds.reshape(-1, 2) - torch.flip(gts.reshape(-1, 2), dims=(1,))),axis=1)
loss = torch.min(diff,diff2)
print(loss)

tensor([0.1000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000], dtype=torch.float64)


In [ ]:
# Plan
    # Get Swapper working
        # Have this predict which is the start and end point too
    # Fix plotting
    # Test again:
        # Images
        # Warping
        # Distortion
    # Check if loss is a bottleneck...probably not
        

In [5]:
start_points = gts[2] if gts.shape[0] > 2 else np.zeros(gts.shape[-1])

In [6]:
np.zeros(gts.shape[-1])

array([0., 0., 0., 0.])

In [27]:
preds = np.array([[ 0,  1.1,  2,  3],
       [ 5,  4,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47]])


In [30]:
def get_eos_from_sos(sos):
    eos = np.ones(sos.shape[-1])
    eos[:-1] = sos[1:]
    return eos

In [85]:

sos = np.array([1,1,0,0,1,1,0,0,0,1,1,1])
#eos = np.array([0,0,1,1,0,0,0,1,1,0,0,1])
eos = get_eos_from_sos(sos)

gts = np.repeat(sos, 4).reshape(-1,4)
gts[:,0] = range(len(sos))
#print(s)
s = np.argwhere(sos+eos>1).reshape(-1)
print(s)


print(gts, s, gts[s])
print(gts.shape)
gts[s,2]=0
replacement = gts[s]
replacement[:,2:] = 1,0
print(gts)
x = np.insert(gts, s, [replacement], 0)
x

[ 0  4  9 10 11]
[[ 0  1  1  1]
 [ 1  1  1  1]
 [ 2  0  0  0]
 [ 3  0  0  0]
 [ 4  1  1  1]
 [ 5  1  1  1]
 [ 6  0  0  0]
 [ 7  0  0  0]
 [ 8  0  0  0]
 [ 9  1  1  1]
 [10  1  1  1]
 [11  1  1  1]] [ 0  4  9 10 11] [[ 0  1  1  1]
 [ 4  1  1  1]
 [ 9  1  1  1]
 [10  1  1  1]
 [11  1  1  1]]
(12, 4)
[[ 0  1  0  1]
 [ 1  1  1  1]
 [ 2  0  0  0]
 [ 3  0  0  0]
 [ 4  1  0  1]
 [ 5  1  1  1]
 [ 6  0  0  0]
 [ 7  0  0  0]
 [ 8  0  0  0]
 [ 9  1  0  1]
 [10  1  0  1]
 [11  1  0  1]]


array([[ 0,  1,  1,  0],
       [ 0,  1,  0,  1],
       [ 1,  1,  1,  1],
       [ 2,  0,  0,  0],
       [ 3,  0,  0,  0],
       [ 4,  1,  1,  0],
       [ 4,  1,  0,  1],
       [ 5,  1,  1,  1],
       [ 6,  0,  0,  0],
       [ 7,  0,  0,  0],
       [ 8,  0,  0,  0],
       [ 9,  1,  1,  0],
       [ 9,  1,  0,  1],
       [10,  1,  1,  0],
       [10,  1,  0,  1],
       [11,  1,  1,  0],
       [11,  1,  0,  1]])

In [89]:

sos = np.array([1,1,0,0,1,1,0,0,0,1,1,1])
#eos = np.array([0,0,1,1,0,0,0,1,1,0,0,1])
eos = get_eos_from_sos(sos)

gts = np.repeat(sos, 4).reshape(-1,4)
gts[:,0] = range(len(sos))
#print(s)
s = np.argwhere(sos+eos>1).reshape(-1)
#print(s)

#print(gts, s, gts[s])
#print(gts.shape)
print(gts)
gts[s,2]=0
replacement = gts[s]
replacement[:,2] = 1

x = np.insert(gts, s, [replacement], 0)
x

[[ 0  1  1  1]
 [ 1  1  1  1]
 [ 2  0  0  0]
 [ 3  0  0  0]
 [ 4  1  1  1]
 [ 5  1  1  1]
 [ 6  0  0  0]
 [ 7  0  0  0]
 [ 8  0  0  0]
 [ 9  1  1  1]
 [10  1  1  1]
 [11  1  1  1]]


array([[ 0,  1,  1,  1],
       [ 0,  1,  0,  1],
       [ 1,  1,  1,  1],
       [ 2,  0,  0,  0],
       [ 3,  0,  0,  0],
       [ 4,  1,  1,  1],
       [ 4,  1,  0,  1],
       [ 5,  1,  1,  1],
       [ 6,  0,  0,  0],
       [ 7,  0,  0,  0],
       [ 8,  0,  0,  0],
       [ 9,  1,  1,  1],
       [ 9,  1,  0,  1],
       [10,  1,  1,  1],
       [10,  1,  0,  1],
       [11,  1,  1,  1],
       [11,  1,  0,  1]])

In [52]:
print(gts)

[1 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1
 1 1 1 0 0 0 0 0 0 0 0]
