In [1]:
import torch
import numpy as np  
from torch import nn, tensor, Tensor
from torch.nn import functional as F 


In [109]:
rel_x = np.random.randint(0,10,20)
rel_x = np.array(range(0,20))
rel_y = np.random.randint(0,10,20)
rel_y = np.array(range(0,20))
start = np.random.randint(0,2,20)

gt = np.c_[rel_x, rel_y, start][np.newaxis] # add batch and channel
gt = gt.transpose(0,2,1) # BATCH, CHANNELS (3), LENGTH
kernel = np.cumsum([.1]*10)
inverse_kenel
#gt = rel_x[np.newaxis, np.newaxis]


In [90]:
print(gt)
print(gt.shape)
print(kernel)


[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
  [ 0  4  5  4  4  0  4  1  9  6  1  5  6  7  5  5  4  1  7  8]
  [ 1  1  0  0  1  1  1  1  0  1  1  1  1  1  0  0  0  0  1  1]]]
(1, 3, 20)
[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [92]:
#m = nn.Conv1d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')
channels = 3
conv = nn.Conv1d(channels, channels, 10, stride=1, padding=9, dilation=1, groups=1, bias=False, padding_mode='zeros')


with torch.no_grad():
    conv.weight = nn.Parameter(Tensor(kernel).repeat(1, channels, 1))
    print(conv.weight)
out = conv(Tensor(gt))
print(out.size())
print(out[:,:,:20])


Parameter containing:
tensor([[[0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
          0.9000, 1.0000],
         [0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
          0.9000, 1.0000],
         [0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
          0.9000, 1.0000]]], requires_grad=True)


RuntimeError: expected stride to be a single integer value or a list of 1 values to match the convolution dimensions, but got stride=[1, 1]

In [108]:
#m = nn.Conv1d(in_channels, out_channels, kernel_size, stride=1, padding=0, dilation=1, groups=1, bias=True, padding_mode='zeros')
channels = 1
conv = nn.Conv2d(1, 1, 10, stride=1, padding=[0,9], dilation=1, groups=1, bias=False, padding_mode='zeros')

conv.weight = nn.Parameter(Tensor(kernel).repeat(1, channels, 1, 1))
print(conv.weight)

out = conv(Tensor(gt[np.newaxis]))
print(out.size())
print(out[:,:,:,:20])


Parameter containing:
tensor([[[[0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
           0.9000, 1.0000]]]], requires_grad=True)
torch.Size([1, 1, 3, 29])
tensor([[[[ 0.0000,  1.0000,  2.9000,  5.6000,  9.0000, 13.0000, 17.5000,
           22.4000, 27.6000, 33.0000, 38.5000, 44.0000, 49.5000, 55.0000,
           60.5000, 66.0000, 71.5000, 77.0000, 82.5000, 88.0000],
          [ 0.0000,  4.0000,  8.6000, 11.7000, 14.4000, 12.7000, 15.0000,
           13.9000, 20.7000, 23.6000, 20.9000, 22.1000, 24.2000, 27.2000,
           27.9000, 28.5000, 27.6000, 23.7000, 25.8000, 29.1000],
          [ 1.0000,  1.9000,  1.7000,  1.5000,  2.3000,  3.0000,  3.6000,
            4.1000,  3.5000,  3.9000,  4.2000,  4.5000,  4.8000,  5.0000,
            4.1000,  3.3000,  2.6000,  2.0000,  2.5000,  2.9000]]]],
       grad_fn=<SliceBackward>)


In [44]:
## Functional approach
weights = tensor(kernel).repeat(1, 1, 1)
print(weights.shape, gt.shape)

output = F.conv1d(tensor(gt), weights)
# torch.nn.functional.conv1d(input, weight, bias=None, stride=1, padding=0, dilation=1, groups=1


torch.Size([1, 1, 10]) (20, 3)


RuntimeError: Expected 3-dimensional input for 3-dimensional weight 1 1 10, but got 2-dimensional input of size [20, 3] instead

In [24]:
weights = tensor([[0.0, 0, 0], [0, 1, 0], [0, 0, 0]]).unsqueeze(0).unsqueeze(0)
weights.requires_grad = True

conv = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=1, bias=False)

with torch.no_grad():
    conv.weight = nn.Parameter(weights)


NameError: name 'x' is not defined

In [37]:
weights = torch.tensor([[0., 0., 0.],
                        [0., 1., 0.],
                        [0., 0., 0.]])
weights = weights.view(1, 1, 3, 3) 
print(weights)
weights = weights.repeat(1, nb_channels, 1, 1)
print(weights)

tensor([[[[0., 0., 0.],
          [0., 1., 0.],
          [0., 0., 0.]]]])
tensor([[[[0., 0., 0.],
          [0., 1., 0.],
          [0., 0., 0.]]]])


In [43]:
weights = tensor([[0.0, 0, 0], [0, 1, 0], [0, 0, 0]]).unsqueeze(0).unsqueeze(0)
weights.requires_grad = True

conv = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=1, bias=False)

with torch.no_grad():
    conv.weight = nn.Parameter(weights)


In [ ]:
# I have input of dimension 32 x 100 x 1 where 32 is the batch size.
# I wanted to convolved over 100 x 1 array in the input for each of the 32 such arrays i.e. a single data point in the batch has an array like that.
# I hoped that conv1d(100, 100, 1) layer will work.

import torch
from torch import nn

a = torch.randn(32, 100, 1)  
m = nn.Conv1d(100, 100, 1) 
out = m(a)
print(out.size())
print(m)


In [10]:
import numpy as np
x = np.array([0,.4,1,1.4,2,2.9,3.6,4,5])

In [11]:
np.argwhere(np.round(x[1:])!=np.round(x[:-1]))+1

array([[2],
       [4],
       [5],
       [6],
       [8]])

In [4]:
%reload_ext autoreload
%autoreload 2

import sys, os
sys.path.append("../../")
sys.path.append("../")
import numpy as np
from stroke_recovery import conv_window
import torch
from torch import Tensor

gt_length = 20
rel_x = np.array(range(0,gt_length))
rel_y = np.random.randint(0, 10, 20)
start = np.random.randint(0, 2, gt_length)

gt = np.c_[rel_x, rel_y, start][np.newaxis]  # BATCH, WIDTH, HEIGHT/VOCAB
pred = gt.copy()
pred[:, 7, 0] = 12

pred = Tensor(pred)  # relative
gt = Tensor(gt)
gt_rel = Tensor(gt)
gt = torch.cumsum(gt, dim=1)  # abs

for conv_func in [conv_window]:
    print(conv_func)
    # Anything with itself should be equivalent to a cumulative sum
    x = conv_func(gt,gt_rel.clone())
    np.testing.assert_almost_equal(x.numpy(), gt, decimal=5)

    # Should get back on track
    x = conv_func(gt,pred.clone())
    np.testing.assert_almost_equal(x[:,-4:].numpy(), gt[:,-4:], decimal=5)
    np.testing.assert_almost_equal(x[:,0:6].numpy(), gt[:,0:6], decimal=5)

    # With batching
    gt2 = Tensor(np.r_[gt,gt])
    gt2_rel = Tensor(np.r_[gt_rel.clone(),gt_rel.clone()]) # pred is relative
    x = conv_func(gt2,gt2_rel)
    np.testing.assert_almost_equal(x.numpy(), gt2, decimal=5)

    # With batching + index
    gt2 = Tensor(np.r_[gt,gt])
    gt2_rel = Tensor(np.r_[gt_rel.clone(),gt_rel.clone()]) # pred is relative
    x = conv_func(gt2,gt2_rel, indices=[0,2])
    np.testing.assert_almost_equal(x.numpy()[:,:,1], gt2_rel[:,:,1], decimal=5)
    np.testing.assert_almost_equal(x.numpy()[:,:,0], gt2[:,:,0], decimal=5)

print(gt_rel)
print(gt)
print(x)

<function conv_window at 0x7f3ada696a60>
tensor([[[ 0.,  4.,  0.],
         [ 1.,  8.,  1.],
         [ 2.,  9.,  1.],
         [ 3.,  2.,  0.],
         [ 4.,  7.,  1.],
         [ 5.,  1.,  1.],
         [ 6.,  9.,  1.],
         [ 7.,  3.,  1.],
         [ 8.,  6.,  1.],
         [ 9.,  7.,  0.],
         [10.,  3.,  0.],
         [11.,  9.,  0.],
         [12.,  3.,  0.],
         [13.,  0.,  0.],
         [14.,  1.,  1.],
         [15.,  7.,  1.],
         [16.,  0.,  0.],
         [17.,  3.,  1.],
         [18.,  9.,  0.],
         [19.,  5.,  0.]]])
tensor([[[  0.,   4.,   0.],
         [  1.,  12.,   1.],
         [  3.,  21.,   2.],
         [  6.,  23.,   2.],
         [ 10.,  30.,   3.],
         [ 15.,  31.,   4.],
         [ 21.,  40.,   5.],
         [ 28.,  43.,   6.],
         [ 36.,  49.,   7.],
         [ 45.,  56.,   7.],
         [ 55.,  59.,   7.],
         [ 66.,  68.,   7.],
         [ 78.,  71.,   7.],
         [ 91.,  71.,   7.],
         [105.,  72.,   8.],
  