In [ ]:
array = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(array)[0]
start_point_ct = len(start_indices)
total_point_ct = len(array)
end_indices = np.append((start_indices-1)[1:], total_point_ct-1)

xs = np.array(range(0, total_point_ct))*1.5
x = np.interp(xs, np.append(start_indices*1.0, end_indices), np.append(np.ones(start_point_ct), np.zeros(start_point_ct)))

print(x, xs, np.append(start_indices*1.0, end_indices))

In [ ]:
array = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(array)[0]
start_point_ct = len(start_indices)
total_point_ct = len(array)
xs = np.repeat(start_indices,2)
xs[::2] -= 1
xs = np.append(xs[1:], total_point_ct)
ys = np.zeros(2*start_point_ct)
ys[1::2] += 1
print(xs, ys)

# make it distance traveled!

interp_xs = np.array(range(0, total_point_ct))
out = np.interp(interp_xs, xs, ys)
print(out)

In [ ]:
x = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(x)
#end_indices = start_indices-1

print(start_indices)

In [ ]:
m = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
np.append(m, 599, 5)

TypeError: 'RClass' object is not callable

In [61]:
array = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(array)[0]
start_point_ct = len(start_indices)
total_point_ct = len(array)
end_indices = np.append((start_indices-1)[1:], total_point_ct)

xs = np.array(range(0, total_point_ct))*1.5
x = np.interp(xs, np.append(start_indices*1.0, end_indices), np.append(np.ones(start_point_ct), np.zeros(start_point_ct)))

print(x, xs, np.append(start_indices*1.0, end_indices))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0.] [ 0.   1.5  3.   4.5  6.   7.5  9.  10.5 12.  13.5 15.  16.5 18.  19.5
 21.  22.5 24. ] [ 0.  8. 14.  7. 13. 17.]


In [79]:
array = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(array)[0]
start_point_ct = len(start_indices)
total_point_ct = len(array)
xs = np.repeat(start_indices,2)
xs[::2] -= 1
xs = np.append(xs[1:], total_point_ct)
ys = np.zeros(2*start_point_ct)
ys[1::2] += 1
print(xs, ys)

# make it distance traveled!

interp_xs = np.array(range(0, total_point_ct))
out = np.interp(interp_xs, xs, ys)
print(out)

[ 0  7  8 13 14 17] [0. 1. 0. 1. 0. 1.]
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         0.         0.2        0.4        0.6
 0.8        1.         0.         0.33333333 0.66666667]


In [ ]:
x = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(x)
#end_indices = start_indices-1

print(start_indices)

In [36]:
m = np.array([1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0])
np.append(m, 599, 5)

IndexError: index 599 is out of bounds for axis 0 with size 17

In [2]:
import numpy as np
def calc_distance(x,y):
    return ((x[:-1] - x[1:])**2+(y[:-1] - y[1:])**2)**(1/2)

def calc_stroke_distances(x,y,start_strokes):
    [start_indices] = np.where(m)
    total_point_ct = len(start_strokes)
    end_indices = np.append((start_indices-1)[1:], total_point_ct-2) # one because legnth is +1, one because length is shortened after calculating distance
    distances = calc_distance(x,y)
    cum_sum = np.cumsum(distances)
    lengths = cum_sum[end_indices]
    return lengths

x = np.array(range(0,17))#**2
y = np.array(range(0,17))#**2
m = np.array([1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0])
calc_stroke_distances(x,y,m)

array([ 4.24264069, 11.3137085 , 19.79898987, 22.627417  ])

In [3]:
start_points = np.array([1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0])
start_indices = np.where(start_points)[0]
start_point_ct = len(start_indices)
total_point_ct = len(start_points)

# Create list of start and end points (x's for interpolation)
xs = np.repeat(start_indices,2)
xs[::2] -= 1
xs = np.append(xs[1:], total_point_ct)

## Create y's for interpolation (the target values)
ys = np.zeros(2*start_point_ct)

# Make each stroke length 1
#ys[1::2] += 1

# Make each target the actual stroke length
distances = calc_stroke_distances(x,y, start_points)
ys[1::2] = distances
print(xs, ys)

interp_xs = np.array(range(0, total_point_ct))
out = np.interp(interp_xs, xs, ys)
print(out)

[ 0  2  3  7  8 13 14 17] [ 0.          4.24264069  0.         11.3137085   0.         19.79898987
  0.         22.627417  ]
[ 0.          2.12132034  4.24264069  0.          2.82842712  5.65685425
  8.48528137 11.3137085   0.          3.95979797  7.91959595 11.87939392
 15.8391919  19.79898987  0.          7.54247233 15.08494467]


In [33]:
len([1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0])

17

In [35]:
np.fromstring("""[0.         1.41421356 2.82842712 0.         1.41421356 2.82842712, 4.24264069 5.65685425 0.
                               1.41421356 2.82842712 4.24264069 5.65685425 7.07106781 0.         1.41421356 2.82842712]""")

<ipython-input-35-94f2b4b76aa7>:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  np.fromstring("""[0.         1.41421356 2.82842712 0.         1.41421356 2.82842712, 4.24264069 5.65685425 0.


ValueError: string size must be a multiple of element size

In [43]:
from ast import literal_eval
import numpy as np
import re 
a = """[0.,         1.41421356 2.82842712 0.         1.41421356 2.82842712 4.24264069 5.65685425 0.  1.41421356 2.82842712 4.24264069 5.65685425 7.07106781 0.         1.41421356 2.82842712]"""
def to_numpy(array_string):
    from ast import literal_eval
    import numpy as np
    import re
    array_string = re.sub('\s+', ',', array_string)
    array_string = np.array(literal_eval(array_string))
    return array_string
to_numpy(a)

SyntaxError: invalid syntax (<unknown>, line 1)

In [50]:
print(m)
print(m[slice(5,None)])

[1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0]
[0 0 0 1 0 0 0 0 0 1 0 0]


In [4]:
import sys
sys.path.append("..")
import stroke_recovery 

In [8]:
x = np.array(range(0,17))#**2
y = np.array(range(0,17))#**2
is_start_stroke = np.array([1,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0])

print(x.shape)
stroke_recovery.get_stroke_length_gt(x, y, is_start_stroke).shape


(17,)


(17,)

In [55]:
x = np.array(range(0,100)).reshape(10,-1)


In [61]:
x[(2,3),:][:,(2,3,9,8)]

array([[22, 23, 29, 28],
       [32, 33, 39, 38]])

In [64]:
pred_opts = [1,1,1,"cumsum"]
[i for i,x in enumerate(pred_opts) if x=="cumsum"]


[3]