In [168]:
%reload_ext autoreload
%autoreload 2

import sys
sys.path.append("../../")
sys.path.append("../")
import os

import pydtw
import numpy as np
from pydtw import dtw
from hwr_utils.stroke_recovery import relativefy_numpy

def start_point_eval(pred, targ, already_stroke_number=False):
    """

    Args:
        pred:
        targ:

    Returns:

    """
    
    pred = np.asarray(pred).astype(float)
    targ = np.asarray(targ).astype(float)
        
    # give preds/targs
    # dynamic time warp them
    # assign the pred the "true" stroke number
    # compare first item in each stroke
    if False:
        if not already_stroke_number:
            pred = relativefy_numpy(pred, reverse=True)
            targ = relativefy_numpy(targ, reverse=True)

        slc = slice(0,2)
        slc = 0
        x1 = np.ascontiguousarray(pred[:,slc])  # time step, (x,y)
        x2 = np.ascontiguousarray(targ[:,slc])
        dist, cost, a, b = dtw.dtw2d(x1, x2)  # dist, cost, a, b
        pred = pred[a, 0:3]
        targ = targ[b, 0:3]
        return pred, targ
    else:
        x1 = pred
        x2 = targ
        dist, cost, a, b = dtw.dtw1d(x1, x2, )  # dist, cost, a, b
        return pred, targ, dist, cost, a, b


AttributeError: module 'pydtw' has no attribute 'version'

In [216]:
from dtaidistance.dtw import warping_paths, distance
np.set_printoptions(precision=2)

# xx1 = x1
# xx2 = x2
# x1 = xx1.copy()
# x2 = xx2.copy()
# x1 = np.array([.8,2,3,4,5,5.1,5,4,2])
# x2 = np.array([1,1.2,3,4,4,3.5,2,1])
# x1 = np.array([1,2.9,2.9,3])
# x2 = np.array([1.1,1.2,1.4,3])
# x1 = np.array([1,1.2,2.9,3])
# x2 = np.array([1,1.2,1.4,3])
x1 = np.random.random(100)
x2 = np.random.random(100)

dist, cost, a, b = dtw.dtw1d(x1, x2, )
print("DTW Original")
print(a)
print(b)
print(cost)
print("My cost", np.sum(np.abs(x1[a]-x2[b])))

alignment = dtw2(x1, x2, keep_internals=True)
print("DTW Italian")
print(alignment.index1)
print(alignment.index2)
print(alignment.distance)
print("My cost", np.sum(np.abs(x1[alignment.index1]-x2[alignment.index2])))
print(alignment.costMatrix)

print("DTAI")
path = dtai(x1,x2)
path = np.c_[[x[0] for x in path],[x[1] for x in path]].transpose(1,0)
print(path)
print(distance(x1,x2))
print("My cost", np.sum(np.abs(x1[path[0]]-x2[path[1]])))
m = warping_paths(x1,x2)
print(m[1])

assert np.allclose(alignment.index1[-8:], np.array(a)[-8:])
assert np.allclose(alignment.index2[-8:], np.array(b)[-8:])

DTW Original
[0, 0, 1, 2, 3, 4, 5, 6, 6, 7, 7, 8, 8, 9, 10, 10, 11, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 30, 31, 32, 32, 33, 34, 34, 35, 35, 35, 36, 37, 38, 38, 39, 39, 40, 41, 42, 43, 44, 44, 44, 45, 46, 47, 48, 49, 50, 50, 51, 52, 53, 54, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 71, 72, 72, 73, 73, 73, 73, 74, 75, 76, 77, 78, 79, 79, 79, 79, 80, 81, 82, 83, 84, 84, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[0, 0, 1, 1, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 18, 19, 20, 20, 21, 22, 23, 23, 23, 23, 23, 23, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 51, 51, 51, 52, 53, 54, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 84, 85, 86, 87, 88, 89, 90, 90, 90, 91, 92, 93, 94, 94, 94, 94, 94, 95, 95, 96, 96, 97, 97, 98, 

AssertionError: 

In [180]:
from dtaidistance.dtw import warping_path as dtai


x1 = np.array([.8,2,3,4,5,5.1,5,4,2])
x2 = np.array([1,1.2,3,4,4,3.5,2,1])
# x1 = np.tile(np.array([1,2.0,3]),[2,1])
# x2 = np.tile(np.array([1,1.2,3]),[2,1])
x1 = np.array([1,1.2,3,4])
x2 = np.array([1,1.2,1.2,4])

x1 = np.array([1,2.0,3])
x2 = np.array([1,1.2,3])


dist, cost, a, b = dtw.dtw1d(x1, x2, )
print(a)
print(b)
print(dist, cost)

alignment = dtw2(x1, x2)
print(alignment.index1)
print(alignment.index2)
print(alignment.distance)
#print(alignment.cost_matrix)
print(alignment.__dict__)

## DTAI 
dtai(x2, x1)



[0, 0, 1, 2]
[0, 0, 1, 2]
<MemoryView of 'ndarray' object> 0.0
[0 0 1 2]
[0 1 1 2]
1.0
{'stepPattern': <dtw.stepPattern.StepPattern object at 0x7f3d848897c0>, 'N': 3, 'M': 3, 'openEnd': False, 'openBegin': False, 'windowFunction': <function noWindow at 0x7f3cdb8cea60>, 'windowArgs': {}, 'jmin': 2, 'distance': 1.0, 'normalizedDistance': 0.16666666666666666, 'index1': array([0, 0, 1, 2]), 'index2': array([0, 1, 1, 2]), 'index1s': array([0, 0, 1, 2]), 'index2s': array([0, 1, 1, 2]), 'stepsTaken': array([2, 3, 1], dtype=int32)}


AssertionError: 

In [177]:
#### 2D VERSION ####
#from dtaidistance.dtw_ndim import warping_path as dtai2d

x1 = np.array([.8,2,3,4,5,5.1,5,4,2])
x2 = np.array([1,1.2,3,4,4,3.5,2,1])
x1 = np.tile(np.array([1,2.0,3]),[2,1])
x2 = np.tile(np.array([1,1.2,3]),[2,1])

print(np.ascontiguousarray(x1))
dist, cost, a, b = dtw.dtw2d(np.ascontiguousarray(x1), np.ascontiguousarray(x2), )
print(a)
print(b)

print(cost)
alignment = dtw2(x1.transpose(1,0), x2.transpose(1,0))
print(alignment.index1)
print(alignment.index2)
print(alignment.distance)

dtai2d(x1, x2)

[[1. 2. 3.]
 [1. 2. 3.]]
[0, 0, 1]
[0, 0, 1]
0.0
[0 0 1 2]
[0 1 1 2]
1.4142135623730951


(1.1313708498984762,
 array([[0.        ,        inf,        inf],
        [       inf, 0.8       , 1.13137085],
        [       inf, 1.13137085, 1.13137085]]))

In [90]:
import numpy as np

pred = np.array([.8,2,3,4,5,5.1,5,4,2])
targ = np.array([1,1.2,3,4,4,3.5,2,1])
# pred = np.random.random(10)
# targ = np.random.random(10)
# pred = [1, 2, 3, 5, 5, 5, 6]
# targ = [1, 1, 2, 2, 3, 5, 6]

#targ = np.array([1,1,3,3,4,3,5])
out_pred, out_targ, dist, cost, a, b = start_point_eval(pred, targ)
out_pred, out_targ, dist, cost, a, b

(array([0.8, 2. , 3. , 4. , 5. , 5.1, 5. , 4. , 2. ]),
 array([1. , 1.2, 3. , 4. , 4. , 3.5, 2. , 1. ]),
 <MemoryView of 'ndarray' at 0x7f3cd6999a00>,
 20.999999999999996,
 [0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 8],
 [0, 0, 1, 2, 3, 3, 3, 4, 5, 6, 7])

In [91]:
from dtw import dtw as dtw2
alignment = dtw2(pred, targ, keep_internals=True)
print(alignment.index1, alignment.index2)
#print(alignment.index1s, alignment.index2s)
print(alignment.distance)
#alignment.plot(type="threeway")
assert np.allclose(alignment.index1, np.array(a))
assert np.allclose(alignment.index2, np.array(b))

[0 0 1 2 3 4 5 6 7 7 8 8] [0 1 1 2 3 3 3 3 4 5 6 7]
6.0


ValueError: operands could not be broadcast together with shapes (12,) (11,) 

In [166]:
from dtaidistance.dtw import distance_fast as dtai_cost
x1 = np.random.random(1000)
x2 = np.random.random(1000)

d = dtw2(x1, x2, keep_internals=False).distance # italian guy
print(d)
c,d,a,b = dtw.dtw1d(x1, x2, ) # pydtw
print(d)
dtai_cost(x1, x2, ) # dtai

213.26126831979022
inf


5.546709035504583

In [150]:
import cProfile
from dtaidistance.dtw import distance_fast
from dtaidistance.dtw import warping_paths_fast as dtai

x1 = np.random.random(1000)
x2 = np.random.random(1000)

def dtw_new():
    for i in range(10):
        dtw2(x1, x2, keep_internals=False)
    
def dtw_old():
    for i in range(10):
        dtw.dtw1d(x1, x2, )

            
def dtw_new2():
    for i in range(10):
        dtai(x1, x2, )
        #distance_fast(x1,x2)
        
cProfile.run('dtw_new()', )
cProfile.run('dtw_old()', )
cProfile.run('dtw_new2()', )

# pr = cProfile.Profile()
# pr.enable()
# for line in fileinput.input():
#     for i in range(10):
#         y = int(line.strip()) + int(line.strip())
# pr.disable()
# pr.print_stats(sort='time')



         73974 function calls (73914 primitive calls) in 0.361 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       10    0.000    0.000    0.000    0.000 <__array_function__ internals>:2(amax)
       20    0.000    0.000    0.000    0.000 <__array_function__ internals>:2(atleast_2d)
       30    0.000    0.000    0.035    0.001 <__array_function__ internals>:2(copyto)
       30    0.000    0.000    0.000    0.000 <__array_function__ internals>:2(empty_like)
       30    0.000    0.000    0.036    0.001 <__array_function__ internals>:2(full_like)
        1    0.000    0.000    0.361    0.361 <ipython-input-150-24c332c276ea>:8(dtw_new)
        1    0.000    0.000    0.361    0.361 <string>:1(<module>)
       20    0.000    0.000    0.000    0.000 _asarray.py:141(ascontiguousarray)
       20    0.000    0.000    0.000    0.000 _asarray.py:16(asarray)
       20    0.000    0.000    0.000    0.000 _asarray.py:88(asanyarray)
 

In [ ]:
import cProfile

pred = np.random.random(1000)
targ = np.random.random(1000)

def dtw_new2():
    for i in range(10):
        dtw2(pred, targ, keep_internals=False)
    
def dtw_old2():
    for i in range(10):
        dtw.dtw2d(x1, x2, )

            
def dtw_new22():
    for i in range(10):
        dtai(x1, x2, )
    
cProfile.run('dtw_new2()', )
cProfile.run('dtw_old2()', )
cProfile.run('dtw_new22()', )

# pr = cProfile.Profile()
# pr.enable()
# for line in fileinput.input():
#     for i in range(10):
#         y = int(line.strip()) + int(line.strip())
# pr.disable()
# pr.print_stats(sort='time')



In [5]:
print(pred[a], targ[b])

[1 1 2 3 4 5 6 7] [1 1 1 3 4 5 6 7]


In [5]:
import json
from pathlib import Path

sample_path = Path("../../data/synthetic_online/train_synth_sample.json")
path = "../../data/synthetic_online/train_synth_full.json"

with Path(sample_path).open() as f:
    d = json.load(f)
    


In [31]:
# Save out sample
# sample_path = Path("../../data/synthetic_online/train_synth_sample.json")

# with outpath.open("w") as f:
#     json.dump(obj=d[:100], fp=f)


In [19]:
from hwr_utils.stroke_recovery import *
def process_synthetic(item):
    """ An item from the master dictionary

    Args:
        item: 

    Returns:

    """
    s = np.array(item["stroke"])
    eos = np.argwhere(s[:,2]).reshape(-1)+1
    new_format = np.split(s[:,:2], eos )

    stroke_dict = prep_stroke_dict(new_format, time_interval=0, scale_time_distance=True) # list of dictionaries, 1 per file
    all_substrokes = get_all_substrokes(stroke_dict, desired_num_of_strokes=None) # subdivide file into smaller sets

    dataset = "train"

    new_items = []

    for i, sub_stroke_dict in enumerate(all_substrokes):
        x_to_y = sub_stroke_dict.x_to_y

        # Don't warp images too much
        if self.square and (x_to_y < .5 or x_to_y > 2):
            continue

        new_img_path = (self.new_img_folder / (file_name + f"_{i}")).with_suffix(".tif")

        new_item = {
            "image_path": new_img_path.relative_to(self.absolute_data_folder).as_posix(),
            "dataset": dataset
        }
        new_item.update(sub_stroke_dict) # added to what's already in the substroke dictionary

        # Create images
        ratio = 1 if self.square else x_to_y

        if self.render_images:
            draw_strokes(normalize_stroke_list(sub_stroke_dict.raw), ratio, save_path=new_img_path, line_width=.8)
        new_items.append(new_item)

    ## Add shapes -- the system needs some time to actually perform the writing op before reading it back
    for item in new_items:
        new_img_path = self.absolute_data_folder / item["image_path"]
        shape = cv2.imread(new_img_path.as_posix()).shape
        item["shape"] = shape
        #ratio = item["x_to_y"]
        #print(shape, 61*ratio)
    return new_items

item = d[0]
print(item.keys())


process_synthetic(item)

dict_keys(['text', 'stroke'])
(17,)
(13,)
(33,)
(13,)
(4,)
(33,)
(17,)
(37,)
(13,)
(9,)
(17,)
(60,)
(81,)
(17,)
(52,)
(73,)
(29,)
(45,)
(45,)
BREAK


NameError: name 'self' is not defined

In [21]:
s = np.array(item["stroke"])
eos = np.argwhere(s[:,2]).reshape(-1)+1
new_format = np.split(s[:,:2], eos )
print(new_format[0][:,0])

[31.69343758 31.68729782 31.72816658 31.83592415 32.01568985 32.20843887
 32.35407257 32.4292717  32.43508911 32.4041481  32.40582657 32.45942688
 32.54905319 32.63677216 32.6637001  32.63510132 32.59074783]


In [31]:
raw_format = []
_idx = 0
for stroke in new_format:
    t = stroke[:,2] if stroke.shape[-1]>2 else np.array(range(len(stroke)))
    raw_format += [{"x":stroke[:,0], "y":stroke[:,1], "time":t}]
print(raw_format)

[{'x': array([31.69343758, 31.68729782, 31.72816658, 31.83592415, 32.01568985,
       32.20843887, 32.35407257, 32.4292717 , 32.43508911, 32.4041481 ,
       32.40582657, 32.45942688, 32.54905319, 32.63677216, 32.6637001 ,
       32.63510132, 32.59074783]), 'y': array([  8.71434307,   8.73089886,   8.54401684,   7.95188093,
         6.78933716,   5.07556868,   2.94575   ,   0.60396719,
        -1.74805427,  -3.94125819,  -5.88361216,  -7.53432989,
        -8.82356834,  -9.68306446, -10.07136536, -10.11333656,
        -9.98889732]), 'time': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])}, {'x': array([25.44309616, 25.43162537, 25.58594704, 26.06929207, 27.05017281,
       28.52864075, 30.42643166, 32.56620407, 34.75837326, 36.81397629,
       38.63234711, 39.9432373 , 40.69979095]), 'y': array([10.6222744 , 10.6122818 , 10.5444212 , 10.39119911, 10.15314198,
        9.9022007 ,  9.72967911,  9.71314812,  9.92642307, 10.35876179,
       10.92545986, 11.437897

In [22]:
naive_t = np.array(range(len(s)))

In [23]:
naive_t

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [32]:
print(item)

{'text': 'This latter anthology', 'stroke': [[31.693437576293945, 8.714343070983887, 0.0], [31.687297821044922, 8.7308988571167, 0.0], [31.728166580200195, 8.54401683807373, 0.0], [31.83592414855957, 7.951880931854248, 0.0], [32.015689849853516, 6.789337158203125, 0.0], [32.208438873291016, 5.075568675994873, 0.0], [32.35407257080078, 2.9457499980926514, 0.0], [32.42927169799805, 0.6039671897888184, 0.0], [32.435089111328125, -1.7480542659759521, 0.0], [32.40414810180664, -3.941258192062378, 0.0], [32.405826568603516, -5.883612155914307, 0.0], [32.45942687988281, -7.534329891204834, 0.0], [32.54905319213867, -8.823568344116211, 0.0], [32.63677215576172, -9.683064460754395, 0.0], [32.663700103759766, -10.071365356445312, 0.0], [32.635101318359375, -10.113336563110352, 0.0], [32.59074783325195, -9.988897323608398, 1.0], [25.443096160888672, 10.622274398803711, 0.0], [25.431625366210938, 10.612281799316406, 0.0], [25.585947036743164, 10.544421195983887, 0.0], [26.069292068481445, 10.39119

In [158]:
from dtaidistance.dtw import distance_fast
import torch
import random

class DynamicNet(torch.nn.Module):
  def __init__(self, D_in, H, D_out):
    """
    In the constructor we construct three nn.Linear instances that we will use
    in the forward pass.
    """
    super(DynamicNet, self).__init__()
    self.input_linear = torch.nn.Linear(D_in, H)
    self.middle_linear = torch.nn.Linear(H, H)
    self.output_linear = torch.nn.Linear(H, D_out)

  def forward(self, x):
    """
    For the forward pass of the model, we randomly choose either 0, 1, 2, or 3
    and reuse the middle_linear Module that many times to compute hidden layer
    representations.

    Since each forward pass builds a dynamic computation graph, we can use normal
    Python control-flow operators like loops or conditional statements when
    defining the forward pass of the model.

    Here we also see that it is perfectly safe to reuse the same Module many
    times when defining a computational graph. This is a big improvement from Lua
    Torch, where each Module could be used only once.
    """
    h_relu = self.input_linear(x).clamp(min=0)
    for _ in range(random.randint(0, 3)):
      h_relu = self.middle_linear(h_relu).clamp(min=0)
    y_pred = self.output_linear(h_relu)
    return y_pred

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random Tensors to hold inputs and outputs.
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)

gt = torch.randn(N, D_out)

model = DynamicNet(D_in, H, D_out)


# Construct our loss function and an Optimizer. Training this strange model with
# vanilla stochastic gradient descent is tough, so we use momentum
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4, momentum=0.9)
for t in range(500):
  # Forward pass: Compute predicted y by passing x to the model
  y_pred = model(x)

  # Compute and print loss
  loss = distance_fast(y_pred, gt)
  print(t, loss.item())

  # Zero gradients, perform a backward pass, and update the weights.
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

TypeError: a bytes-like object is required, not 'Tensor'