In [1]:
%reload_ext autoreload
%autoreload 2

import sys
sys.path.append("../../")
sys.path.append("../")
sys.path.append("/media/data/GitHub/simple_hwr")
import os
import numpy as np
from hwr_utils import *
from hwr_utils.stroke_plotting import *
from hwr_utils.stroke_recovery import *
import json
from matplotlib import pyplot as plt

In [2]:
import numpy as np

x = np.array([1,2])
y = x
x = x[::-1]
print(y)

[1 2]


In [3]:
gt = np.array(range(36)).reshape(9,4)
gt[:,2] = [1,0,0,1,0,1,0,0,0]
print(gt)

[[ 0  1  1  3]
 [ 4  5  0  7]
 [ 8  9  0 11]
 [12 13  1 15]
 [16 17  0 19]
 [20 21  1 23]
 [24 25  0 27]
 [28 29  0 31]
 [32 33  0 35]]


In [34]:
import numpy as np
threshold=.1
sos_index=2
gt = np.array(range(36)).reshape(9,4)
gt[:,2] = [1,0,0,1,0,1,0,0,0]
gt[-1,:] = [3.4,5,1,1]
print(gt)

sos_args = get_sos_args(gt[:,sos_index], stroke_numbers=False)
strokes = np.split(gt, sos_args)[1:]
print(strokes)
avg_x_position = [np.mean(s[:,0]) for s in strokes if s.size]
avg_x_position += np.cumsum([threshold]*len(avg_x_position)) # this acts like a threshold, but increases for larger stroke swaps

print(avg_x_position)
x = list(zip(strokes, avg_x_position))
x.sort(key=lambda m: m[1])
np.concatenate([i[0] for i in x])

[[ 0  1  1  3]
 [ 4  5  0  7]
 [ 8  9  0 11]
 [12 13  1 15]
 [16 17  0 19]
 [20 21  1 23]
 [24 25  0 27]
 [28 29  0 31]
 [ 3  5  1  1]]
[array([[ 0,  1,  1,  3],
       [ 4,  5,  0,  7],
       [ 8,  9,  0, 11]]), array([[12, 13,  1, 15],
       [16, 17,  0, 19]]), array([[20, 21,  1, 23],
       [24, 25,  0, 27],
       [28, 29,  0, 31]]), array([[3, 5, 1, 1]])]
[ 4.1 14.2 24.3  3.4]


array([[ 3,  5,  1,  1],
       [ 0,  1,  1,  3],
       [ 4,  5,  0,  7],
       [ 8,  9,  0, 11],
       [12, 13,  1, 15],
       [16, 17,  0, 19],
       [20, 21,  1, 23],
       [24, 25,  0, 27],
       [28, 29,  0, 31]])

In [16]:
x

[(array([], shape=(0, 4), dtype=int64), 1.25),
 (array([[0, 1, 1, 3]]), 5.5),
 (array([[ 4,  5,  0,  7],
         [ 8,  9,  0, 11]]),
  10.25),
 (array([[12, 13,  1, 15]]), 13.0),
 (array([[16, 17,  0, 19]]), 16.25),
 (array([[20, 21,  1, 23]]), 22.0)]