In [146]:
import numpy as np
import torch
from torch import tensor, Tensor

%reload_ext autoreload
%autoreload 2

import sys
sys.path.append("../../")
from models.start_points import *

shape = 2,5,4
#x = np.array(range(0,np.product(shape))).reshape(*shape)

size = np.product(shape)
gt = np.random.randint(0,2,size).reshape(*shape)
print(gt)
gt[:,:,3] = 0
gt[:,-1,3] = 1

gt = [i for i in gt]
MAX_LEN=100
# np.r_[x[x[:,2]>0],x[x[:,3]>0]]
start_points = [np.delete(x[np.logical_or(x[:,2]>0,x[:,3]>0)],2,-1)[:MAX_LEN] for x in gt]
x = gt[0]
start_points



[[[1 0 1 1]
  [1 0 0 1]
  [0 0 1 0]
  [1 1 0 1]
  [0 1 0 1]]

 [[0 0 0 0]
  [1 1 1 0]
  [0 1 1 0]
  [1 0 0 0]
  [0 1 0 0]]]


[array([[1, 0, 0],
        [0, 0, 0],
        [0, 1, 1]]), array([[1, 1, 0],
        [0, 1, 0],
        [0, 1, 1]])]

In [138]:
x[np.logical_or(x[:,2]>0,x[:,2]>0)] == x[x[:,2]>0]

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [26]:
def WithNumpy(seq, keep, skip):
    return seq.reshape((-1, keep+skip))[:,:keep+1].flatten()

IndexError: index 3 is out of bounds for axis 1 with size 2

array([ True, False,  True,  True,  True])

In [65]:
s = StartPointModel2()
shape = 3,1,60,400        start_points = np.r_[gt[gt[:,2]>0],gt[gt[:,3]>0]][:MAX_LEN] # could end with the EOS point 2x if also a start stroke, NBD

s(Tensor(range(0,np.product(shape))).reshape(*shape))

INFO:root.models.CoordConv:Larger X Coord: False
INFO:root.models.CoordConv:Normal X Coord: True
INFO:root.models.CoordConv:Using 2 X Coord Channels: False


torch.Size([101, 3, 1024])


tensor([[[ 0.1081,  0.0229,  0.1164],
         [ 0.0897,  0.0282,  0.0114],
         [-0.0165,  0.0706,  0.1276]],

        [[ 0.0854,  0.0293,  0.0449],
         [ 0.1016,  0.0405, -0.0354],
         [ 0.0290,  0.0814,  0.0249]],

        [[ 0.0703,  0.0401,  0.0039],
         [ 0.0897,  0.0427, -0.0537],
         [ 0.0449,  0.0781, -0.0242]],

        [[ 0.0650,  0.0423, -0.0155],
         [ 0.0750,  0.0509, -0.0598],
         [ 0.0428,  0.0663, -0.0462]],

        [[ 0.0545,  0.0423, -0.0284],
         [ 0.0664,  0.0514, -0.0532],
         [ 0.0445,  0.0618, -0.0460]],

        [[ 0.0511,  0.0464, -0.0325],
         [ 0.0563,  0.0508, -0.0478],
         [ 0.0478,  0.0566, -0.0436]],

        [[ 0.0477,  0.0487, -0.0341],
         [ 0.0533,  0.0494, -0.0444],
         [ 0.0501,  0.0538, -0.0436]],

        [[ 0.0475,  0.0522, -0.0326],
         [ 0.0508,  0.0544, -0.0396],
         [ 0.0478,  0.0530, -0.0402]],

        [[ 0.0466,  0.0527, -0.0335],
         [ 0.0492,  0.0556, -0.036