In [14]:
import torch
import sys, os
sys.path.append("./simple_hwr")
print(os.getcwd())
import crnn
from pathlib import Path

folder = Path("/media/SuperComputerGroups/fslg_hwr/taylor_simple_hwr/results/BEST/20190831_220233-baseline_warp_online4_occlusion")
load = folder / "baseline_warp_online4_model.pt"
save = folder / "only_the_state.pt"



/media/data/GitHub


In [15]:
x = torch.load(load)



/home/taylor/anaconda3/envs/hw2/lib/python3.7/site-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.container.Sequential' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/taylor/anaconda3/envs/hw2/lib/python3.7/site-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.activation.ReLU' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/taylor/anaconda3/envs/hw2/lib/python3.7/site-packages/torch/serialization.py:454: SourceChangeWarning: source code of class 'torch.nn.modules.rnn.LSTM' has changed. you can retrieve the original so

In [16]:
torch.save(x["model"], save)

In [4]:
import numpy as np
x = np.array([1,2,3])
y = x[1:2]
y -= 5
print(x,y)

[ 1 -3  3] [-3]


In [20]:
import torch
m = torch.Tensor(range(0,27)).reshape(3,3,3)
print(m)
print(m[:,:,0])

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.]],

        [[ 9., 10., 11.],
         [12., 13., 14.],
         [15., 16., 17.]],

        [[18., 19., 20.],
         [21., 22., 23.],
         [24., 25., 26.]]])
tensor([[ 0.,  3.,  6.],
        [ 9., 12., 15.],
        [18., 21., 24.]])


In [25]:
l = m.clone()
l[:,:,0] = torch.cumsum(m[:,:,0], dim=1)
print(l)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 9.,  7.,  8.]],

        [[ 9., 10., 11.],
         [21., 13., 14.],
         [36., 16., 17.]],

        [[18., 19., 20.],
         [39., 22., 23.],
         [63., 25., 26.]]])
